import pandas as pd

df = pd.read_csv('altcoin_season_history.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])

print('=' * 60)
print('Altcoin Season Index - Data Summary')
print('=' * 60)
print(f'Total records: {len(df)}')
print(f'Date range: {df["timestamp"].min()} to {df["timestamp"].max()}')
print()
print('Index Statistics:')
print(f'  Current (latest): {df["index_value"].iloc[-1]:.1f}')
print(f'  Minimum: {df["index_value"].min():.1f}')
print(f'  Maximum: {df["index_value"].max():.1f}')
print(f'  Average (1 year): {df["index_value"].mean():.1f}')
print(f'  Last 7 days avg: {df["index_value"].tail(7).mean():.1f}')
print(f'  Last 30 days avg: {df["index_value"].tail(30).mean():.1f}')
print()
print('Season Distribution:')
btc_season = len(df[df['index_value'] <= 25])
mixed = len(df[(df['index_value'] > 25) & (df['index_value'] < 75)])
alt_season = len(df[df['index_value'] >= 75])
print(f'  Bitcoin Season (<25): {btc_season} days ({btc_season/len(df)*100:.1f}%)')
print(f'  Mixed Market (25-75): {mixed} days ({mixed/len(df)*100:.1f}%)')
print(f'  Altcoin Season (>75): {alt_season} days ({alt_season/len(df)*100:.1f}%)')
print('=' * 60)
